name: nextmove_app
description: Mobility mode prediction app for NextMove project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP requests
  http: ^1.1.0
  
  # Location services
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  
  # State management
  provider: ^6.0.5
  
  # Data persistence
  shared_preferences: ^2.2.2
  
  # UI enhancements
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0
  
  # Phone number input
  intl_phone_field: ^3.2.0
  
  # Pin code input for OTP
  pin_code_fields: ^8.0.1
  
  # Enhanced features
  connectivity_plus: ^5.0.2
  flutter_local_notifications: ^17.2.3
  flutter_secure_storage: ^9.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  
  # Charts and analytics
  fl_chart: ^0.66.0
  
  # Image handling
  cached_network_image: ^3.3.0
  
  # App lifecycle
  app_settings: ^5.1.1
  
  # Background tasks
  flutter_background_service: ^5.0.5
  workmanager: ^0.9.0
  
  # Motion sensors
  sensors_plus: ^4.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true